version: '3'
services:
  postgres:
    image: postgres
    container_name: postgres_container
    environment:
      POSTGRES_USER: bookstore_user
      POSTGRES_PASSWORD: your_password
      POSTGRES_DB: bookstore_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:

